title: Ilya Ploshchik # your name (or website title) here
logo: "/images/Profil bilde.JPG" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <h> Welcome and thanks for vitisiting my simple portfolio. <h> <br>
  Here I am gathering the ML and data analytics projects and scripts created during studies and hobby projects <br>
  Feel free to use code if found interested
  <br><br>
  <a href="https://www.linkedin.com/in/ilyaploshchik/">View My LinkedIn Profile</a> <br>
  <a href=mailto:ilyaploshchik@gmail.com>Please send me an e-email for any enquires</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-199369842-1 # your Google Analytics tracking ID here
