title: Ilya Ploshchik # your name (or website title) here
logo: "/images/Profil bilde.JPG" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Welcome and thanks for vitisiting my simple portfolio <br>
  Here I am gathering the ML and data analytics projects and scripts created during studies and as hobby self-study projects
  <br><br>
  <a href="https://www.linkedin.com/in/ilyaploshchik/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-199369842-1 # your Google Analytics tracking ID here
