title: Ilya Ploshchik # your name (or website title) here
logo: "/images/Profil bilde.JPG" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  My ML and data analytics projects and scripts
  <br><br>
  <a href="https://www.linkedin.com/in/ilyaploshchik/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-merlot
google_analytics: UA-199369842-1 # your Google Analytics tracking ID here
